if ( NOT WIN32 )
    option(WITH_ICONV "Build csync with iconv support" ON)
endif()
option(UNIT_TESTING "Build with unit tests" OFF)
option(MEM_NULL_TESTS "Enable NULL memory testing" OFF)
option(WITH_LOCAL_PLUGINDIR "Makes csync look for backend modules in the same directory as the executable" OFF)
option(WITH_STATIC_LIB "Builds libcsync as a static library in addition to the shared one. The static will have _static prepended to the base name" OFF)